export enum EventType {
    CRIME = 'CRIME',
    ARREST = 'ARREST',
    INTERROGATION = 'INTERROGATION',
    SURVEILLANCE = 'SURVEILLANCE',
    COURT_HEARING = 'COURT_HEARING',
    INCIDENT = 'INCIDENT'
}
